### ISSUE TITLE
Section TBD: Need an Examples Landing Page

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/fhir-ae-research-ig#11]
URLs:
http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/AdverseEvent-ClinicalResearchAdverseEventexample1.html
http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/AdverseEvent-ClinicalResearchAdverseEventUseCase7.html

There are other example references at the bottom of this page. 
http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/artifacts.html

Comment: Need an examples landing page directory.

**Comment by bheale** [comment]
added a draft under 'Background and Workflow' menu item called 'Real World examples'

**Comment by bheale** [comment]
done
