### ISSUE TITLE
Section 2.4: Understanding FHIR

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/fhir-ae-research-ig#2]
URL: http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/index.html#understanding-fhir
Comment: Is this section necessary?

**Comment by mike-hamidi** [comment]
Note: If removed, please delete the reference under Section 2.2 stating, "Those new to FHIR should review the Understanding FHIR section below."

**Comment by bheale** [comment]
@mike-hamidi thanks for the issues. I will be addressing them in the next few days

**Comment by bheale** [comment]
The section, or something like it, appears in many other IGs. It has served as a way to remind implementers that the IG builds off the core specification and that one should review the core specification. We could certainly edit the boiler-plate to be more specific.

**Comment by mike-hamidi** [comment]
Let's keep it if its consistently applied. Not a major issue.

**Comment by bheale** [comment]
closed

**Comment by bheale** [comment]
closed
