### ISSUE TITLE
Section 2.2: Direct Resource Link

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/fhir-ae-research-ig#3]
URL: http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/index.html#how-to-use-this-guide
Comment: Can we link the "AdverseEvent" resource reference text directly? Generally, I think it's helpful to do this we calling out FHIR resources or attributes.

**Comment by bheale** [comment]
What do you think about linking to the Clinical Research Profile there?

**Comment by mike-hamidi** [comment]
Agreed.

**Comment by bheale** [comment]
done
