### ISSUE TITLE
Section 8.7.1: AE Seriousness - Simple Correction

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/fhir-ae-research-ig#7]
URL: http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/ValueSet-adverse-event-seriousness-criteria-vs.html
Comment: Can we update the "(e.g. Medwatch forms)" to "(e.g. Form FDA 3500A MedWatch)"

**Comment by bheale** [comment]
done
