### ISSUE TITLE
Section 8.7.1: Incorrect ICH Reference

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/fhir-ae-research-ig#8]
URL: http://build.fhir.org/ig/HL7/fhir-ae-research-ig/branches/master/ValueSet-adverse-event-seriousness-criteria-vs.html#root
Comment: The current reference is to ICH E2B(R3) Individual Case Safety Report (ICSR) Specification and Related Files, which should be updated to indicate ICH E2D Post-Approval Safety Data Management: Definitions and Standards for Expedited Reporting. The link is correct.

Existing Text:
This list comes from ICH E2B R3 (https://database.ich.org/sites/default/files/E2D_Guideline.pdf).

Recommended Text:
"The adverse event seriousness criteria value set is based on the ICH E2D Post-Approval Safety Data Management: Definitions and Standards for Expedited Reporting guidance (https://database.ich.org/sites/default/files/E2D_Guideline.pdf)."

**Comment by bheale** [comment]
corrected in commit
